- name: "create.domain: Ensure present domain"
  virt_domain_config:
    spec:    "{{ darkbulb_topology.compute | to_xml }}"
    format:  "xml"
    state:   "present"

- name: "create.domain: Ensure started domain"
  virt_domain_config:
    spec:    "{{ darkbulb_topology.compute | to_xml }}"
    format:  "xml"
    state:   "started"
