- name: "create.domain: Define domain [{{ darkbulb_topology.compute.domain.name }}]"
  virt:
    name:       "{{ darkbulb_topology.compute.domain.name }}"
    xml:        "{{ darkbulb_topology.compute | to_xml }}"
    command:    "define"

- name: "create.domain: Ensure running domain [{{ darkbulb_topology.compute.domain.name }}]"
  virt:
    name:       "{{ darkbulb_topology.compute.domain.name }}"
    xml:        "{{ darkbulb_topology.compute | to_xml }}"
    state:      "running"
    autostart:  yes
