- name: "domain: Define domain"
  virt:
    name:       "{{ darkbulb_topology.compute.domain.name }}"
    xml:        "{{ darkbulb_topology.compute | to_xml }}"
    command:    "define"

- name: "domain: Ensure state of domain"
  virt:
    name:       "{{ darkbulb_topology.compute.domain.name }}"
    xml:        "{{ darkbulb_topology.compute | to_xml }}"
    state:      "running"
    autostart:  yes
