- name: "create.domain: Ensure running domain"
  virt:
    name:       "{{ darkbulb_topology.compute.domain.name }}"
    xml:        "{{ darkbulb_topology.compute | to_xml }}"
    state:      "running"
    autostart:  yes
