- name: "domain: Define domain [{{jxml.value.domain.name}}]"
  virt:
    name:       "{{ jxml.value.domain.name }}"
    xml:        "{{ jxml.value | to_xml }}"
    command:    "define"

- name: "domain: Ensure state of domain [{{jxml.value.domain.name}}]"
  virt:
    name:       "{{ jxml.value.domain.name }}"
    xml:        "{{ jxml.value | to_xml }}"
    state:      "running"
    autostart:  yes
