- name: "create.domain: Ensure presence"
  virt:
    name: "{{ topology_builder.compute.domain.name }}"
    xml: "{{ topology_builder.compute | to_xml }}"
    state: "present"

- name: "create.domain: Ensure running"
  virt:
    name: "{{ topology_builder.compute.domain.name }}"
    state: "running"

- name: "create.domain: Ensure autostart"
  virt:
    name: "{{ topology_builder.compute.domain.name }}"
    autostart:  "yes"
