- name: "create.network: Ensure presence"
  virt_net:
    name:       "{{ topology_builder.network.network.name }}"
    xml:        "{{ topology_builder.network | to_xml }}"
    state:      "present"

- name: "create.network: Ensure active"
  virt_net:
    name:       "{{ topology_builder.network.network.name }}"
    state:      "active"

- name: "create.network: Ensure autostart"
  virt_net:
    name:       "{{ topology_builder.network.network.name }}"
    autostart:  "yes"
