- name: "network: Define network"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    xml:        "{{ darkbulb_topology.network | to_xml }}"
    command:    "define"

- name: "network: Create network"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    xml:        "{{ darkbulb_topology.network | to_xml }}"
    state:      "present"

- name: "network: Activate network"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    xml:        "{{ darkbulb_topology.network | to_xml }}"
    state:      "active"
