- name: "create.network: Define network [{{ darkbulb_topology.network.network.name }}]"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    xml:        "{{ darkbulb_topology.network | to_xml }}"
    command:    "define"

- name: "create.network: Ensure present network [{{ darkbulb_topology.network.network.name }}]"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    xml:        "{{ darkbulb_topology.network | to_xml }}"
    state:      "present"

- name: "create.network: Ensure active network [{{ darkbulb_topology.network.network.name }}]"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    xml:        "{{ darkbulb_topology.network | to_xml }}"
    state:      "active"
