- name: "create.pool: Ensure presence"
  virt_pool:
    name:   "{{ topology_builder.storagepool.pool.name }}"
    xml:    "{{ topology_builder.storagepool | to_xml }}"
    state:  "present"

- name: "create.pool: Ensure active"
  virt_pool:
    name:   "{{ topology_builder.storagepool.pool.name }}"
    state:  "active"

- name: "create.pool: Ensure autostart"
  virt_pool:
    name:       "{{ topology_builder.storagepool.pool.name }}"
    autostart:  "yes"
