- name: "create.pool: Ensure present pool"
  virt_pool:
    name:       "{{ darkbulb_topology.storagepool.pool.name }}"
    xml:        "{{ darkbulb_topology.storagepool | to_xml }}"
    state:      "present"
    autostart:  yes
