- name: "volume: Generate configuration file"
  copy:
    content:    "{{ darkbulb_topology.storagevol | to_xml }}"
    dest:       "{{ darkbulb_topology.config.path }}/pools/{{ darkbulb_topology.storagevol.volume.name }}"
    owner:      "{{ darkbulb_topology.config.user }}"
    group:      "{{ darkbulb_topology.config.group }}"
    validate: /usr/bin/virt-xml-validate %s storagevol

- name: "volume: Create volume"
  command:
    virsh vol-create \
    --file      "{{ darkbulb_topology.config.path }}/pools/{{ darkbulb_topology.storagevol.volume.name }}" \
    --pool      "{{ darkbulb_topology.storagepool.pool.name }}"
  args:
    creates:    "{{ darkbulb_topology.storagepool.pool.target.path }}/{{ darkbulb_topology.storagevol.volume.name }}"
