- name: "create.volume: Generate configuration"
  copy:
    content:    "{{ topology_builder.storagevol | to_xml }}"
    dest:       "{{ topology_builder.config.path }}/volumes/{{ topology_builder.storagevol.volume.name }}"
# Buggy virt-xml-validate
#    validate: /usr/bin/virt-xml-validate %s storagevol

- name: "create.volume: Ensure presence"
  command:
    virsh -c qemu:///system \
      vol-create \
        --file      "{{ topology_builder.config.path }}/volumes/{{ topology_builder.storagevol.volume.name }}" \
        --pool      "{{ topology_builder.storagepool.pool.name }}"
  args:
    chdir:  "{{ topology_builder.storagepool.pool.target.path }}"
    creates:  "{{ topology_builder.storagevol.volume.name }}"
