- name: "create: Ensure directory configurations"
  file:
    path:         "{{ topology_builder.config.path }}/{{ config_dir }}"
    state:        directory
  loop:           "{{ topology_builder.config.dirs }}"
  loop_control:
    loop_var:     config_dir

- name: "create: Process Network"
  include_tasks:  "create/network.yml"

- name: "create: Process Storage Pool"
  include_tasks:  "create/pool.yml"

- name: "create: Process Storage Volume"
  include_tasks:  "create/volume.yml"

- name: "create: Process Compute Domain"
  include_tasks:  "create/domain.yml"
