- name: "create: Ensure directory configurations"
  file:
    path:         "{{ darkbulb_topology.config.path }}/{{ config_dir }}"
    owner:        "{{ darkbulb_topology.config.user }}"
    group:        "{{ darkbulb_topology.config.group }}"
    state:        directory
  loop:           "{{ darkbulb_topology.config.dirs }}"
  loop_control:
    loop_var:     config_dir

- name: "create: Process Network"
  include_tasks:  "create/network.yml"
  when: darkbulb_topology.network.network is defined

- name: "create: Process Storage Pool"
  include_tasks:  "create/pool.yml"
  when: darkbulb_topology.storagepool.pool is defined

- name: "create: Process Storage Volume"
  include_tasks:  "create/volume.yml"
  when: darkbulb_topology.storagevol.volume is defined

- name: "create: Process Compute Domain"
  include_tasks:  "create/domain.yml"
  when: darkbulb_topology.compute.domain is defined
