- name: "Load variables"
  include_tasks:  "load.yml"

- name: "Set darkbulb_topology"
  set_fact:
    darkbulb_topology: "{{ __darkbulb_topology | combine( darkbulb_topology, recursive=True ) }}"

- name: "destroy: Ensure state of configuration directories"
  file:
    path:         "{{ darkbulb_topology.config.path }}/{{ config_dir }}"
    owner:        "{{ darkbulb_topology.config.user }}"
    group:        "{{ darkbulb_topology.config.group }}"
    state:        directory
  loop:           "{{ darkbulb_topology.config.dirs }}"
  loop_control:
    loop_var:     config_dir

- name: "destroy: Process Compute Domain"
  include_tasks:  "destroy/domain.yml"
  when:           darkbulb_topology.domain is defined

- name: "destroy: Process Storage Volume"
  include_tasks:  "destroy/volume.yml"
  when:           darkbulb_topology.storagevol is defined

- name: "destroy: Process Storage Pool"
  include_tasks:  "destroy/pool.yml"
  when:           darkbulb_topology.storagepool is defined

- name: "destroy: Process Network"
  include_tasks:  "destroy/network.yml"
  when:           darkbulb_topology.network is defined

- name: "destroy: Delete configuration directories"
  file:
    path:         "{{ darkbulb_topology.config.path }}"
    state:        absent
