- name: "destroy: Process Compute Domain"
  include_tasks:  "destroy/domain.yml"

- name: "destroy: Process Storage Volume"
  include_tasks:  "destroy/volume.yml"

- name: "destroy: Ensure absent configuration directories"
  file:
    path:         "{{ topology_builder.config.path }}"
    state:        "absent"
