- name: "Validate instances configuration files"
  command:
    virt-xml-validate \
      "{{ darkbulb_topology_config_path.remote }}/instances/{{ instance_config_file.path }}"
      domain

- name: "Ensure state of Instance"
  block:
    - name: "Create Instance"
      command:
        virsh create \
          "{{ darkbulb_topology_config_path.remote }}/instances/{{ instance_config_file.path }}" \

  rescue:
    - name: "Instance already exists"
      command: /bin/true
