- name: "network: Generate configuration file for [{{jxml.value.domain.name}}]"
  copy:
    content: "{{ jxml.value | to_xml }}"
    dest: "{{ darkbulb_topology.config.path }}/networks/{{ jxml.value.network.name }}"
    owner: "{{ darkbulb_topology.config.user }}"
    group: "{{ darkbulb_topology.config.group }}"
    validate: /usr/bin/virt-xml-validate %s network

- name: "network: Create network [{{jxml.value.domain.name}}]"
  command:
    virsh net-create \
      "{{ darkbulb_topology.config.path }}/networks/{{ jxml.value.network.name }}"
  args:
    creates: "/etc/libvirt/qemu/networks/{{ jxml.value.network.name }}.xml"
