- name: "pool: Generate pool's configuration file for [{{jxml.value.pool.name}}]"
  copy:
    content: "{{ jxml.value | to_xml }}"
    dest: "{{ darkbulb_topology.config.path }}/pools/{{ jxml.value.pool.name }}"
    owner: "{{ darkbulb_topology.config.user }}"
    group: "{{ darkbulb_topology.config.group }}"
    validate: /usr/bin/virt-xml-validate %s storagepool

- name: "pool: Create pool [{{jxml.value.pool.name}}]"
  command:
    virsh pool-create \
      "{{ darkbulb_topology.config.path }}/pools/{{ jxml.value.pool.name }}"
  args:
    creates: "/etc/libvirt/storage/{{ jxml.value.pool.name }}.xml"
