__config:
  dirs:
  -             "domains"
  -             "volumes"
  -             "pools"
  -             "networks"
  group:        "darkbulb"
  path:         "/home/darkbulb/config/"
  user:         "darkbulb"
  image:        "default.img"
  state:        "present"
