- name: "destroy.domain: Destroy domain [{{ darkbulb_topology.compute.domain.name }}]"
  virt:
    name:       "{{ darkbulb_topology.compute.domain.name }}"
    xml:        "{{ darkbulb_topology.compute | to_xml }}"
    command:    "destroy"

- name: "destroy.domain: Undefine domain [{{ darkbulb_topology.compute.domain.name }}]"
  virt:
    name:       "{{ darkbulb_topology.compute.domain.name }}"
    xml:        "{{ darkbulb_topology.compute | to_xml }}"
    command:    "undefine"
