- name: "network: Inactivate network"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    command:    "destroy"

- name: "network: Ensure state of network"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    command:    "undefine"
