- name: "destroy.network: Destroy network [{{ darkbulb_topology.network.network.name }}]"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    command:    "destroy"

- name: "destroy.network: Undefine network [{{ darkbulb_topology.network.network.name }}]"
  virt_net:
    name:       "{{ darkbulb_topology.network.network.name }}"
    command:    "undefine"
