- name: "network: Ensure state of pool"
  virt_pool:
    name:     "{{ darkbulb_topology.storagepool.pool.name }}"
    state:    "inactive"

- name: "network: Ensure state of pool"
  virt_pool:
    name:     "{{ darkbulb_topology.storagepool.pool.name }}"
    state:    "absent"
