- name: "destroy.network: Ensure absent pool"
  virt_pool:
    name:       "{{ darkbulb_topology.storagepool.pool.name }}"
    xml:        "{{ darkbulb_topology.storagepool | to_xml }}"
    autostart:  "no"
    state:      "absent"
