- name: "destroy.volume: Ensure absence"
  command:
    virsh -c qemu:///system \
      vol-delete \
      --vol     "{{ topology_builder.storagevol.volume.name }}" \
      --pool    "{{ topology_builder.storagepool.pool.name }}"
  args:
    chdir:  "{{ topology_builder.storagepool.pool.target.path }}"
    removes:  "{{ topology_builder.storagevol.volume.name }}"
