- name: "destroy.volume: Generate configuration for volume: [{{ darkbulb_topology.storagevol.volume.name }}]"
  copy:
    content:    "{{ darkbulb_topology.storagevol | to_xml }}"
    dest:       "{{ darkbulb_topology.config.path }}/pools/{{ darkbulb_topology.storagevol.volume.name }}"
    owner:      "{{ darkbulb_topology.config.user }}"
    group:      "{{ darkbulb_topology.config.group }}"
    validate: /usr/bin/virt-xml-validate %s storagevol

- name: "destroy.volume: Delete volume [{{ darkbulb_topology.storagevol.volume.name }}]"
  command:
    virsh vol-delete \
    --vol     "{{ darkbulb_topology.config.path }}/pools/{{ darkbulb_topology.storagevol.volume.name }}" \
    --pool    "{{ darkbulb_topology.storagepool.pool.name }}"
  args:
    creates:  "{{ darkbulb_topology.storagepool.pool.target.path }}/{{ darkbulb_topology.storagevol.volume.name }}"
